#!/bin/sh

#alias tmux='tmux new-session -A -s main'

alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'

# alias ls='ls -G'
# export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd

alias g++='g++ -std=c++17'

alias vi='nvim'

alias tre='tmux attach'
alias tat='tmux attach-session -t'
alias tkt='tmux kill-session -t'
alias tst='tmux switch -t'
alias tns='tmux new -s'
alias tls='tmux ls'
alias ofd='open .'

alias live-server='live-server --port=8080 --browser=chromium'

alias bat='bat --style=plain'
alias 'bat -nu'='bat --style=numbers'

