#!/bin/sh

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line

bindkey '^e' edit-command-line

# bindkey '^[[Z' reverse-menu-complete

bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

bindkey -a k history-beginning-search-backward
bindkey -a j history-beginning-search-forward
