#!/bin/sh

skip_global_compinit=1

zmodload zsh/nearcolor

autoload -U promptinit; promptinit
autoload -Uz compinit

if [[ $CUR_OS == 'linux' ]]; then
    for dump in ~/.zcompdump(N.mh+24); do
        compinit
    done
    compinit -C
elif [[ $CUR_OS == 'mac' ]]; then
    compinit -i
fi
